/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author joaov
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivos = new javax.swing.JMenu();
        btSair = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        btCadastrarUsuarios = new javax.swing.JMenuItem();
        btAlterarUsuarios = new javax.swing.JMenuItem();
        btExcluirUsuarios = new javax.swing.JMenuItem();
        btPesquisarUsuarios = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        btCadastrarClientes = new javax.swing.JMenuItem();
        btAlterarClientes = new javax.swing.JMenuItem();
        btExcluirClientes = new javax.swing.JMenuItem();
        btPesquisarClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btCadastrarFuncionarios = new javax.swing.JMenuItem();
        btAlterarFuncionarios = new javax.swing.JMenuItem();
        btExcluirFuncionarios = new javax.swing.JMenuItem();
        btPesquisarFuncionarios = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        btGerenciarProd = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel de Controle");
        setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        menuArquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        menuArquivos.setText("Arquivos");

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        menuArquivos.add(btSair);

        jMenuBar1.add(menuArquivos);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        menuUsuarios.setText("Usuários");

        btCadastrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        btCadastrarUsuarios.setText("Cadastrar");
        btCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(btCadastrarUsuarios);

        btAlterarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        btAlterarUsuarios.setText("Alterar");
        menuUsuarios.add(btAlterarUsuarios);

        btExcluirUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        btExcluirUsuarios.setText("Excluir");
        menuUsuarios.add(btExcluirUsuarios);

        btPesquisarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        btPesquisarUsuarios.setText("Pesquisar");
        menuUsuarios.add(btPesquisarUsuarios);

        jMenuBar1.add(menuUsuarios);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        menuClientes.setText("Clientes");

        btCadastrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_add.png"))); // NOI18N
        btCadastrarClientes.setText("Cadastrar");
        btCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(btCadastrarClientes);

        btAlterarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        btAlterarClientes.setText("Alterar");
        menuClientes.add(btAlterarClientes);

        btExcluirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_delete.png"))); // NOI18N
        btExcluirClientes.setText("Excluir");
        menuClientes.add(btExcluirClientes);

        btPesquisarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        btPesquisarClientes.setText("Pesquisar");
        menuClientes.add(btPesquisarClientes);

        jMenuBar1.add(menuClientes);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_suit.png"))); // NOI18N
        jMenu3.setText("Funcionários");

        btCadastrarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        btCadastrarFuncionarios.setText("Cadastrar");
        btCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(btCadastrarFuncionarios);

        btAlterarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        btAlterarFuncionarios.setText("Alterar");
        jMenu3.add(btAlterarFuncionarios);

        btExcluirFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        btExcluirFuncionarios.setText("Excluir");
        btExcluirFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(btExcluirFuncionarios);

        btPesquisarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        btPesquisarFuncionarios.setText("Pesquisar");
        jMenu3.add(btPesquisarFuncionarios);

        jMenuBar1.add(jMenu3);

        menuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/script.png"))); // NOI18N
        menuProdutos.setText("Produtos");

        btGerenciarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog.png"))); // NOI18N
        btGerenciarProd.setText("Gerenciar");
        btGerenciarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarProdActionPerformed(evt);
            }
        });
        menuProdutos.add(btGerenciarProd);

        jMenuBar1.add(menuProdutos);

        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        menuSobre.setText("Sobre");
        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarUsuariosActionPerformed
        cadastrousuario cuser = new cadastrousuario();
        jDesktopPane1.add(cuser);
        cuser.setVisible(true);
    }//GEN-LAST:event_btCadastrarUsuariosActionPerformed

    private void btCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClientesActionPerformed
        cadastrocliente ccliente = new cadastrocliente();
        jDesktopPane1.add(ccliente);
        ccliente.setVisible(true);
    }//GEN-LAST:event_btCadastrarClientesActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btGerenciarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarProdActionPerformed
        produtos prod = new produtos();
        jDesktopPane1.add(prod);
        prod.setVisible(true);
    }//GEN-LAST:event_btGerenciarProdActionPerformed

    private void btCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFuncionariosActionPerformed
        cadastrofuncionario cfuncionario = new cadastrofuncionario();
        jDesktopPane1.add(cfuncionario);
        cfuncionario.setVisible(true);
    }//GEN-LAST:event_btCadastrarFuncionariosActionPerformed

    private void btExcluirFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFuncionariosActionPerformed
        excluirfuncionario efuncionario = new excluirfuncionario();
        jDesktopPane1.add(efuncionario);
        efuncionario.setVisible(true);
    }//GEN-LAST:event_btExcluirFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAlterarClientes;
    private javax.swing.JMenuItem btAlterarFuncionarios;
    private javax.swing.JMenuItem btAlterarUsuarios;
    private javax.swing.JMenuItem btCadastrarClientes;
    private javax.swing.JMenuItem btCadastrarFuncionarios;
    private javax.swing.JMenuItem btCadastrarUsuarios;
    private javax.swing.JMenuItem btExcluirClientes;
    private javax.swing.JMenuItem btExcluirFuncionarios;
    private javax.swing.JMenuItem btExcluirUsuarios;
    private javax.swing.JMenuItem btGerenciarProd;
    private javax.swing.JMenuItem btPesquisarClientes;
    private javax.swing.JMenuItem btPesquisarFuncionarios;
    private javax.swing.JMenuItem btPesquisarUsuarios;
    private javax.swing.JMenuItem btSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArquivos;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
